import type { WeldField, WeldFieldKey } from './weld-fields'

export const ACTIONS_COLUMN_WIDTH = 96
export const STAMP_COLUMN_WIDTH = 126
export const REQUEST_COLUMN_WIDTH = 170
export const RESULT_COLUMN_WIDTH = 132

const COMPACT_FIELD_KEYS = new Set<WeldFieldKey>([
  'hasVik',
  'hasRk',
  'hasUzk',
  'hasPvk',
  'hasTvmt',
  'pstoRequired',
  'vikResult',
  'rkResult',
  'uzkResult',
  'pvkResult',
  'tvmtResult',
  'pstoResult',
])

const COLUMN_WIDTHS: Partial<Record<WeldFieldKey, number>> = {
  projectTitle: 112,
  subtitleCode: 112,
  line: 128,
  groupName: 138,
  category: 148,
  weldControlPercent: 104,
  isometry: 168,
  sheet: 96,
  revisionNumber: 108,
  revisionActuality: 138,
  spool: 86,
  spoolId: 90,
  joint: 104,
  officiality: 118,
  orderCode1: 112,
  orderCode2: 112,
  materialUniqueNumber1: 172,
  materialUniqueNumber2: 172,
  element1: 120,
  element2: 120,
  material1: 188,
  material2: 188,
  materialFullName1: 220,
  materialFullName2: 220,
  materialNormativeDocument1: 190,
  materialNormativeDocument2: 190,
  materialCertificateNumber1: 190,
  materialCertificateNumber2: 190,
  elementLength1: 142,
  elementLength2: 142,
  weldingMethod: 104,
  connectionType: 96,
  materialGroup: 132,
  d1: 58,
  d2: 58,
  t1: 58,
  t2: 58,
  wdi: 70,
  weldDate: 112,
  responsible: 132,
  technologyCardNumber: 188,
  weldingElectrodes: 180,
  weldingElectrodesCertificateNumber: 206,
  fillerWire: 180,
  fillerWireCertificateNumber: 206,
  shieldingGas: 156,
  shieldingGasCertificateNumber: 190,
  stamp1K: STAMP_COLUMN_WIDTH,
  stamp1Z: STAMP_COLUMN_WIDTH,
  stamp1O: STAMP_COLUMN_WIDTH,
  stamp2K: STAMP_COLUMN_WIDTH,
  stamp2Z: STAMP_COLUMN_WIDTH,
  stamp2O: STAMP_COLUMN_WIDTH,
  stamp1KFact: STAMP_COLUMN_WIDTH,
  stamp1ZFact: STAMP_COLUMN_WIDTH,
  stamp1OFact: STAMP_COLUMN_WIDTH,
  stamp2KFact: STAMP_COLUMN_WIDTH,
  stamp2ZFact: STAMP_COLUMN_WIDTH,
  stamp2OFact: STAMP_COLUMN_WIDTH,
  vikRequest: REQUEST_COLUMN_WIDTH,
  vikRequestDate: 112,
  rkRequest: REQUEST_COLUMN_WIDTH,
  rkRequestDate: 112,
  uzkRequest: REQUEST_COLUMN_WIDTH,
  uzkRequestDate: 112,
  pvkRequest: REQUEST_COLUMN_WIDTH,
  pvkRequestDate: 112,
  pstoRequest: REQUEST_COLUMN_WIDTH,
  pstoRequestDate: 112,
  pstoDate: 112,
  pstoResult: RESULT_COLUMN_WIDTH,
  pstoCycleSummary: 190,
  heatTreatmentDiagram: RESULT_COLUMN_WIDTH,
  pstoNote: RESULT_COLUMN_WIDTH,
  tvmtRequest: REQUEST_COLUMN_WIDTH,
  tvmtRequestDate: 112,
  finalStatus: RESULT_COLUMN_WIDTH,
  vikResult: RESULT_COLUMN_WIDTH,
  rkResult: RESULT_COLUMN_WIDTH,
  uzkResult: RESULT_COLUMN_WIDTH,
  pvkResult: RESULT_COLUMN_WIDTH,
  tvmtResult: RESULT_COLUMN_WIDTH,
  testTypes: 132,
  testContour: 112,
  testDate: 112,
  piDate: 112,
  boq: 70,
  testBoq: 96,
  piBoq: 96,
  ks3: 70,
  testKs3: 96,
  piKs3: 96,
  createdAt: 120,
  weldingUpdatedAt: 120,
  pstoBoq: 78,
  pstoKs3: 78,
  pstoCreatedAt: 120,
  pstoUpdatedAt: 120,
  lnkCreatedAt: 120,
  lnkUpdatedAt: 120,
  vikBoq: 78,
  vikKs3: 78,
  rkBoq: 78,
  rkKs3: 78,
  uzkBoq: 78,
  uzkKs3: 78,
  pvkBoq: 78,
  pvkKs3: 78,
  tvmtBoq: 86,
  tvmtKs3: 86,
  vikConclusionDate: 112,
  vikConclusion: 150,
  rkConclusionDate: 112,
  rkConclusion: 150,
  uzkConclusionDate: 112,
  uzkConclusion: 150,
  pvkConclusionDate: 112,
  pvkConclusion: 150,
  tvmtConclusionDate: 112,
  tvmtConclusion: 150,
  lnkDefectDescription: 220,
  lnkNote: 180,
  weldingJournalNote: 220,
  jsrDocument: 180,
  checklistDocument: 180,
  zniDocument: 180,
  layeredVikDocuments: 184,
  layeredPvkDocuments: 184,
}

export function getWeldColumnWidth(fieldKey: string) {
  const key = fieldKey as WeldFieldKey
  return COLUMN_WIDTHS[key] ?? (COMPACT_FIELD_KEYS.has(key) ? 82 : 120)
}

export function getWeldTableWidth(fields: readonly WeldField[]) {
  return Math.max(900, fields.reduce((total, field) => total + getWeldColumnWidth(field.key), 0) + ACTIONS_COLUMN_WIDTH)
}

export function isCompactWeldColumn(fieldKey: string) {
  return COMPACT_FIELD_KEYS.has(fieldKey as WeldFieldKey)
}
