import type { WeldField, WeldFieldKey } from './weld-fields'

export const ACTIONS_COLUMN_WIDTH = 96
export const STAMP_COLUMN_WIDTH = 126
export const REQUEST_COLUMN_WIDTH = 170
export const RESULT_COLUMN_WIDTH = 132

const COMPACT_FIELD_KEYS = new Set<WeldFieldKey>([
  'hasVik',
  'hasRk',
  'hasPvk',
  'hasUzk',
  'hasTvmt',
  'hasRfa',
  'hasStls',
  'hasMkk',
  'pstoRequired',
  'vikResult',
  'rkResult',
  'pvkResult',
  'uzkResult',
  'tvmtResult',
  'rfaResult',
  'stlsResult',
  'mkkResult',
  'pstoResult',
])

const COLUMN_WIDTHS: Partial<Record<WeldFieldKey, number>> = {
  projectTitle: 112,
  subtitleCode: 112,
  line: 128,
  groupName: 92,
  category: 92,
  weldControlPercent: 104,
  isometry: 168,
  sheet: 64,
  revisionNumber: 72,
  revisionActuality: 104,
  spool: 86,
  spoolId: 90,
  joint: 104,
  status: 104,
  orderCode1: 112,
  orderCode2: 112,
  element1: 120,
  element2: 120,
  material1: 188,
  material2: 188,
  weldingMethod: 104,
  connectionType: 96,
  d1: 58,
  d2: 58,
  t1: 58,
  t2: 58,
  wdi: 70,
  weldDate: 112,
  responsible: 132,
  stamp1K: STAMP_COLUMN_WIDTH,
  stamp1Z: STAMP_COLUMN_WIDTH,
  stamp1O: STAMP_COLUMN_WIDTH,
  stamp2K: STAMP_COLUMN_WIDTH,
  stamp2Z: STAMP_COLUMN_WIDTH,
  stamp2O: STAMP_COLUMN_WIDTH,
  stamp1KFact: STAMP_COLUMN_WIDTH,
  stamp1ZFact: STAMP_COLUMN_WIDTH,
  stamp1OFact: STAMP_COLUMN_WIDTH,
  stamp2KFact: STAMP_COLUMN_WIDTH,
  stamp2ZFact: STAMP_COLUMN_WIDTH,
  stamp2OFact: STAMP_COLUMN_WIDTH,
  vikRequest: REQUEST_COLUMN_WIDTH,
  rkRequest: REQUEST_COLUMN_WIDTH,
  pvkRequest: REQUEST_COLUMN_WIDTH,
  uzkRequest: REQUEST_COLUMN_WIDTH,
  pstoRequest: REQUEST_COLUMN_WIDTH,
  pstoDate: 112,
  pstoResult: RESULT_COLUMN_WIDTH,
  heatTreatmentDiagram: RESULT_COLUMN_WIDTH,
  pstoNote: RESULT_COLUMN_WIDTH,
  tvmtRequest: REQUEST_COLUMN_WIDTH,
  rfaRequest: REQUEST_COLUMN_WIDTH,
  stlsRequest: REQUEST_COLUMN_WIDTH,
  mkkRequest: REQUEST_COLUMN_WIDTH,
  finalStatus: RESULT_COLUMN_WIDTH,
  vikResult: RESULT_COLUMN_WIDTH,
  rkResult: RESULT_COLUMN_WIDTH,
  pvkResult: RESULT_COLUMN_WIDTH,
  uzkResult: RESULT_COLUMN_WIDTH,
  tvmtResult: RESULT_COLUMN_WIDTH,
  rfaResult: RESULT_COLUMN_WIDTH,
  stlsResult: RESULT_COLUMN_WIDTH,
  mkkResult: RESULT_COLUMN_WIDTH,
  boq: 70,
  ks3: 70,
  createdAt: 120,
  pstoBoq: 78,
  pstoKs3: 78,
  pstoCreatedAt: 120,
  lnkCreatedAt: 120,
  vikBoq: 78,
  vikKs3: 78,
  rkBoq: 78,
  rkKs3: 78,
  pvkBoq: 78,
  pvkKs3: 78,
  uzkBoq: 78,
  uzkKs3: 78,
  tvmtBoq: 86,
  tvmtKs3: 86,
  rfaBoq: 78,
  rfaKs3: 78,
  stlsBoq: 86,
  stlsKs3: 86,
  mkkBoq: 78,
  mkkKs3: 78,
  vikConclusionDate: 112,
  vikConclusion: 150,
  rkConclusionDate: 112,
  rkConclusion: 150,
  pvkConclusionDate: 112,
  pvkConclusion: 150,
  uzkConclusionDate: 112,
  uzkConclusion: 150,
  tvmtConclusionDate: 112,
  tvmtConclusion: 150,
  rfaConclusionDate: 112,
  rfaConclusion: 150,
  stlsConclusionDate: 112,
  stlsConclusion: 150,
  mkkConclusionDate: 112,
  mkkConclusion: 150,
  lnkDefectDescription: 220,
  lnkNote: 180,
}

export function getWeldColumnWidth(fieldKey: string) {
  const key = fieldKey as WeldFieldKey
  return COLUMN_WIDTHS[key] ?? (COMPACT_FIELD_KEYS.has(key) ? 82 : 120)
}

export function getWeldTableWidth(fields: readonly WeldField[]) {
  return Math.max(900, fields.reduce((total, field) => total + getWeldColumnWidth(field.key), 0) + ACTIONS_COLUMN_WIDTH)
}

export function isCompactWeldColumn(fieldKey: string) {
  return COMPACT_FIELD_KEYS.has(fieldKey as WeldFieldKey)
}
