import type { WeldFieldKey } from '@/lib/weld-fields'

export const yesEmptyFieldKeys = new Set([
  'pstoRequired',
  'hasVik',
  'hasRk',
  'hasUzk',
  'hasPvk',
  'hasTvmt',
  'hasRfa',
  'hasStls',
  'hasMkk',
])

export const percentageControlFieldKeys = new Set<WeldFieldKey>(['hasRk', 'hasUzk'])

export const factualWelderStampFieldKeys = new Set<WeldFieldKey>([
  'stamp1KFact',
  'stamp1ZFact',
  'stamp1OFact',
  'stamp2KFact',
  'stamp2ZFact',
  'stamp2OFact',
])

export const secondaryWeldFormSectionNames = new Set(['Код работ', 'Закрытие'])

export const secondaryWeldFormFieldKeys = new Set<WeldFieldKey>([
  'boq',
  'pstoBoq',
  'vikBoq',
  'rkBoq',
  'uzkBoq',
  'pvkBoq',
  'tvmtBoq',
  'rfaBoq',
  'stlsBoq',
  'mkkBoq',
  'ks3',
  'pstoKs3',
  'vikKs3',
  'rkKs3',
  'uzkKs3',
  'pvkKs3',
  'tvmtKs3',
  'rfaKs3',
  'stlsKs3',
  'mkkKs3',
])

export const formHiddenFieldKeys = new Set<WeldFieldKey>([
  'status',
  'createdAt',
  'vikRequest',
  'rkRequest',
  'uzkRequest',
  'pvkRequest',
  'pstoRequest',
  'tvmtRequest',
  'rfaRequest',
  'stlsRequest',
  'mkkRequest',
  'pstoDate',
  'heatTreatmentDiagram',
  'vikResult',
  'rkResult',
  'uzkResult',
  'pvkResult',
  'pstoResult',
  'tvmtResult',
  'rfaResult',
  'stlsResult',
  'mkkResult',
  'pstoNote',
  'finalStatus',
  'pstoCreatedAt',
  'lnkCreatedAt',
  'vikConclusionDate',
  'vikConclusion',
  'rkConclusionDate',
  'rkConclusion',
  'uzkConclusionDate',
  'uzkConclusion',
  'pvkConclusionDate',
  'pvkConclusion',
  'tvmtConclusionDate',
  'tvmtConclusion',
  'rfaConclusionDate',
  'rfaConclusion',
  'stlsConclusionDate',
  'stlsConclusion',
  'mkkConclusionDate',
  'mkkConclusion',
  'lnkDefectDescription',
  'lnkNote',
])
