import { expect, test, type Page } from '@playwright/test'
import { withE2eDatabase } from '../database'
import { cleanupLineProgramProjects } from '../line-program-fixtures'
import { rpcName } from '../rpc'

const project = 'E2E program followup'
test.afterEach(() => cleanupLineProgramProjects([project]))
async function seed(name: string, count = 2) {
  return withE2eDatabase(async db => {
    const { rows: [line] } = await db.query("insert into line_programs (project_title,subtitle_code,line,category,group_name,weld_control_percent,pvk_control_percent) values ($1,'FOLLOWUP',$2,'II','A',30,10) returning id", [project, name])
    await db.query(`insert into weld_joints (line_program_id,project_title,subtitle_code,line,joint,weld_date,connection_type,category,group_name,weld_control_percent,pvk_control_percent,has_vik,stamp_1_k,stamp_1_k_fact,has_rk,has_uzk,rk_result,rk_conclusion,uzk_result,uzk_conclusion)
      select $1,$2,'FOLLOWUP',$3,'F'||n,'2026-09-01','С17','II','A',30,10,'да','FOLLOW-K','FOLLOW-K','да','да','годен','KEEP-RK-'||n,'годен','KEEP-UZK-'||n from generate_series(1,$4::int) n`, [line.id, project, name, count])
    await db.query(`update weld_joints set officiality='действующий',revision_actuality='актуальная',welding_method='РД',material_group='M01',d1=108,d2=108,t1=4,t2=4,wdi=0.42,isometry='ISO-FOLLOW',spool='S1',vik_control_basis='проект',rk_control_basis='проект',uzk_control_basis='проект',pvk_control_basis='проект' where line_program_id=$1`, [line.id])
    if (!(await db.query("select 1 from welder_stamps where naks_stamp='FOLLOW-K'")).rowCount) await db.query(`insert into welder_stamps(naks_stamp,welder_name,weld_type,material_groups,diameter_from,diameter_to,thickness_from,thickness_to,valid_from,valid_to,naks_permits)
      values ('FOLLOW-K','E2E program followup','РД','M01','1','1000','1','100','2026-01-01','2026-12-31','[{"id":"follow","weldType":"РД","materialGroups":"M01","diameterFrom":"1","diameterTo":"1000","thicknessFrom":"1","thicknessTo":"100","validFrom":"2026-01-01","validTo":"2026-12-31","archived":false}]')`)
    return line.id as number
  })
}
async function assignments(page: Page, name: string) {
  await page.goto('/line-program')
  const program = page.getByTestId('line-program')
  await program.getByLabel('Поиск программы линий').fill(name)
  await expect(program.getByTestId('line-program-card')).toHaveCount(1)
  await program.getByTestId('line-program-header').click({ button: 'right' })
  await page.getByTestId('context-action-menu').getByRole('button', { name: 'Назначения', exact: true }).click()
  return page.getByRole('dialog', { name: `Назначения · ${name}` })
}

test('согласование старого выполненного контроля и отмена не меняют историю; отмена диалога безопасна', async ({ page }) => {
  const id = await seed('FOLLOW-APPROVAL')
  const before = await withE2eDatabase(async db => (await db.query('select * from weld_joints where line_program_id=$1 order by id', [id])).rows)
  const calls: string[] = [], errors: string[] = []
  page.on('request', request => { if (request.url().includes('/_serverFn/')) calls.push(rpcName(request.url())) })
  page.on('pageerror', error => errors.push(error.message))
  const modal = await assignments(page, 'FOLLOW-APPROVAL')
  await modal.getByLabel('Выбрать F1', { exact: true }).check()
  await modal.getByRole('button', { name: /Согласовать сочетание/ }).click()
  await page.getByRole('button', { name: 'Вернуться', exact: true }).click()
  await expect(modal.getByText('✓ Согласовано', { exact: true })).toHaveCount(0)
  await modal.getByRole('button', { name: /Согласовать сочетание/ }).click()
  await page.getByRole('button', { name: 'Согласовать', exact: true }).click()
  await expect(modal.getByText('✓ Согласовано', { exact: true })).toHaveCount(1)
  await expect(modal.getByLabel('F1 · РК', { exact: true }).locator('option[value=""]')).toBeDisabled()
  await modal.getByLabel('Выбрать F1', { exact: true }).check()
  await modal.getByLabel('Выбрать F2', { exact: true }).check()
  const mixed = modal.getByLabel('Согласование выбранных стыков')
  await expect(mixed).toBeVisible()
  expect(await mixed.evaluate(el => { const css = getComputedStyle(el); return parseFloat(css.lineHeight) + parseFloat(css.paddingTop) + parseFloat(css.paddingBottom) <= el.clientHeight })).toBe(true)
  await modal.screenshot({ path: 'outputs/program-approval-selection.png' })
  await mixed.selectOption('revoke:combination')
  await page.getByRole('button', { name: 'Снять согласование', exact: true }).click()
  await expect(modal.getByText('✓ Согласовано', { exact: true })).toHaveCount(0)
  await expect(modal.getByLabel('F1 · РК', { exact: true })).toHaveValue('да')
  await expect(modal.getByLabel('F1 · РК', { exact: true }).locator('option[value=""]')).toBeDisabled()
  await withE2eDatabase(async db => {
    expect((await db.query('select * from weld_joints where line_program_id=$1 order by id', [id])).rows).toEqual(before)
    expect((await db.query('select key from dispatcher_accepted_warnings where weld_joint_id=any($1::int[])', [before.map(row => row.id)])).rows).toEqual([])
  })
  expect(calls.filter(name => name.startsWith('changeLineProgramApprovals_'))).toHaveLength(2)
  expect(calls.filter(name => name.startsWith('getLineProgramSection_'))).toHaveLength(1)
  expect(calls.filter(name => name.startsWith('getLineProgramJointPage_'))).toHaveLength(3)
  expect(errors).toEqual([])
  await modal.screenshot({ path: 'outputs/program-approval-actions.png' })
})

test('сводки всех страниц текущего отбора, отдельные клейма и печатный вид без всплывающих окон', async ({ page }) => {
  await page.addInitScript(() => { window.open = () => null })
  const calls: string[] = [], errors: string[] = []
  page.on('request', request => { if (request.url().includes('/_serverFn/')) calls.push(rpcName(request.url())) })
  page.on('pageerror', error => errors.push(error.message))
  await withE2eDatabase(db => db.query(`insert into line_programs(project_title,subtitle_code,line,category,group_name,weld_control_percent,pvk_control_percent)
    select $1,'FOLLOWUP','FOLLOW-REPORT-'||lpad(n::text,2,'0'),'II','A',30,10 from generate_series(1,32) n`, [project]))
  await page.goto('/line-program')
  const program = page.getByTestId('line-program')
  await program.getByLabel('Поиск программы линий').fill('FOLLOW-REPORT-')
  await expect(program.getByText('1–30 из 32 линий', { exact: true })).toBeVisible()
  const show = page.getByRole('button', { name: 'Показать', exact: true })
  expect(await show.evaluate(el => !!el.closest('[data-report-page-header]'))).toBe(true)
  await show.click()
  await expect(page.getByRole('button', { name: 'Сводка по линиям', exact: true })).toBeVisible()
  const triggerBox = (await show.boundingBox())!, optionBox = (await page.getByRole('button', { name: 'Сводка по линиям', exact: true }).boundingBox())!
  expect(Math.abs(optionBox.x + optionBox.width - triggerBox.x - triggerBox.width)).toBeLessThan(8)
  expect(optionBox.y).toBeGreaterThan(triggerBox.y + triggerBox.height)
  await page.screenshot({ path: 'outputs/program-report-menu.png' })
  await page.getByRole('button', { name: 'Сводка по линиям', exact: true }).click()
  const preview = page.getByRole('dialog', { name: 'Предпросмотр отчёта' })
  const report = preview.frameLocator('iframe')
  await expect(report.getByRole('heading', { name: 'Программа линий — сводка по линиям', exact: true })).toBeVisible()
  await expect(report.locator('tbody tr')).toHaveCount(32)
  await expect(report.getByText('FOLLOW-REPORT-32', { exact: true })).toBeVisible()
  await page.emulateMedia({ media: 'print' })
  await expect(report.locator('.toolbar')).toHaveCount(0)
  expect(await report.locator('thead').evaluate(el => getComputedStyle(el).display)).toBe('table-header-group')
  await page.emulateMedia({ media: 'screen' })
  await expect(preview.getByRole('button', { name: 'Печать / Сохранить PDF' })).toBeEnabled()
  await report.locator('body').evaluate(el => { el.ownerDocument.defaultView!.print = () => { el.dataset.printed = 'true' } })
  await preview.getByRole('button', { name: 'Печать / Сохранить PDF' }).click()
  await expect(report.locator('body')).toHaveAttribute('data-printed', 'true')
  await page.evaluate(() => { window.dispatchEvent(new Event('focus')); window.dispatchEvent(new Event('online')) })
  await page.screenshot({ path: 'outputs/program-line-report.png' })
  expect(calls.filter(name => name.startsWith('getLineProgramReport_'))).toHaveLength(1)
  await report.locator('body').press('Escape')
  await expect(preview).toHaveCount(0)
  await expect(show).toBeFocused()
  await expect(program.getByLabel('Поиск программы линий')).toHaveValue('FOLLOW-REPORT-')
  const id = await seed('FOLLOW-STAMP')
  await withE2eDatabase(db => db.query("update weld_joints set stamp_2_k='SECOND-K' where line_program_id=$1", [id]))
  await page.reload()
  await program.getByLabel('Поиск программы линий').fill('FOLLOW-STAMP')
  await expect(program.getByTestId('line-program-card')).toHaveCount(1)
  await show.click()
  await page.getByRole('button', { name: 'Сводка по клеймам', exact: true }).click()
  const stamps = preview.frameLocator('iframe')
  await expect(stamps.locator('tbody tr')).toHaveCount(2)
  await expect(stamps.locator('.metric').filter({ hasText: 'Физических стыков' }).locator('.metric-value')).toHaveText('2')
  await expect(stamps.locator('tbody')).toContainText('SECOND-K')
  await preview.getByRole('button', { name: 'Закрыть предпросмотр' }).click()
  expect(calls.filter(name => name.startsWith('getLineProgramReport_'))).toHaveLength(2)
  expect(errors).toEqual([])
})

test('брак одного стыка заменяет только его ожидания на нет потребности, не меняя назначения и историю', async ({ page }) => {
  const name = 'FOLLOW-NO-NEED', id = await seed(name, 20)
  await withE2eDatabase(db => db.query(`update weld_joints set vik_result='годен',
    has_rk=case when substring(joint from 2)::int<=6 then 'да' else null end,
    rk_result=case when joint='F1' then 'ремонт' when substring(joint from 2)::int<=6 then 'ожидает заявку' else null end,
    rk_conclusion=case when joint='F1' then 'KEEP-RK-1' else null end,
    has_uzk=case when joint='F1' then 'дополнительный' else null end,
    uzk_result=case when joint='F1' then 'ожидает заявку' else null end,uzk_conclusion=null,
    has_pvk=case when substring(joint from 2)::int<=2 then 'дополнительный' else null end,
    pvk_result=case when substring(joint from 2)::int<=2 then 'ожидает заявку' else null end where line_program_id=$1`, [id]))
  const before = await withE2eDatabase(async db => (await db.query('select * from weld_joints where line_program_id=$1 order by id', [id])).rows)
  const modal = await assignments(page, name)
  const result = modal.getByLabel('Результат F1', { exact: true })
  await result.locator('xpath=ancestor::details[1]').locator('summary').click()
  for (const value of ['ВИК: годен', 'РК: ремонт', 'УЗК: нет потребности', 'ПВК: нет потребности']) await expect(result.getByText(value, { exact: true })).toBeVisible()
  await expect(modal.getByLabel('Результат F2', { exact: true })).toContainText('ПВК: ожидает заявку')
  await expect(modal.getByLabel('F1 · УЗК', { exact: true })).toHaveValue('дополнительный')
  await expect(modal.getByLabel('F1 · ПВК', { exact: true })).toHaveValue('дополнительный')
  await page.screenshot({ path: 'outputs/program-no-need.png' })
  await modal.getByRole('button', { name: 'Закрыть назначения' }).click()
  const program = page.getByTestId('line-program')
  const cardHeader = program.getByTestId('line-program-header')
  await expect(cardHeader.getByRole('button', { name: 'РК - УЗК · зачтено / нужно 6 / 8', exact: true })).toBeVisible()
  await expect(cardHeader.getByRole('button', { name: 'ПВК · зачтено / нужно 1 / 2', exact: true })).toBeVisible()
  await expect(cardHeader.getByRole('button', { name: 'К назначению 3', exact: true })).toBeVisible()
  const header = program.getByRole('button', { name: `Расчёт линии ${name}`, exact: true })
  if (await header.getAttribute('aria-expanded') !== 'true') await header.click()
  const all = program.getByRole('button', { name: 'Все стыки линии', exact: true })
  if (await all.getAttribute('aria-pressed') !== 'true') await all.click()
  await expect(all).toHaveAttribute('aria-pressed', 'true')
  const first = program.getByTestId('line-program-readonly-joint').filter({ has: page.getByRole('button', { name: 'F1', exact: true }) })
  await expect(first.getByRole('button', { name: 'УЗК нет потребности', exact: true })).toBeVisible()
  await first.getByRole('button', { name: 'F1', exact: true }).click()
  const history = program.getByLabel('История контроля F1', { exact: true })
  await expect(history.getByText('УЗК: нет потребности', { exact: true })).toBeVisible()
  await expect(history.getByRole('button', { name: 'KEEP-RK-1', exact: true })).toBeVisible()
  const after = await withE2eDatabase(async db => (await db.query('select * from weld_joints where line_program_id=$1 order by id', [id])).rows)
  expect(after).toEqual(before)
})

for (const count of [500, 1000]) test(`окно назначений ${count} стыков с документами: поиск, сохранение и ограниченные запросы`, async ({ page }) => {
  const name = `FOLLOW-LOAD-${count}`, id = await seed(name, count)
  await withE2eDatabase(async db => {
    // Real document relations, not only displayed conclusion strings.
    await db.query(`insert into generated_documents(type,title,file_name,mime_type)
      select type,$1||'-'||type,$1||'-'||type||'.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      from unnest(array['system:lnkRequest','system:lnkConclusionRk']) type`, [name])
    await db.query(`insert into generated_document_weld_joints(document_id,weld_joint_id)
      select d.id,w.id from generated_documents d cross join weld_joints w where d.title like $1 and w.line_program_id=$2`, [name + '-%', id])
    await db.query("update weld_joints set has_uzk=null,uzk_result=null,uzk_conclusion=null,has_pvk=null,rk_request=$2||'-system:lnkRequest',rk_conclusion=$2||'-system:lnkConclusionRk' where line_program_id=$1", [id, name])
  })
  const calls: string[] = [], errors: string[] = [], bytes: Promise<number>[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (request.url().includes('/_serverFn/')) calls.push(rpcName(request.url())) })
  page.on('response', response => { if (response.url().includes('/_serverFn/') && rpcName(response.url()).startsWith('getLineProgramJointPage_')) bytes.push(response.body().then(body => body.length)) })
  const started = performance.now(), modal = await assignments(page, name)
  await expect(modal.getByTestId('line-program-joint')).toHaveCount(50)
  const openedMs = Math.round(performance.now() - started), searchAt = performance.now()
  await modal.getByLabel('Поиск стыков в назначениях').fill(`F${count}`)
  await expect(modal.getByTestId('line-program-joint')).toHaveCount(1)
  const searchMs = Math.round(performance.now() - searchAt)
  const reads = calls.filter(name => name.startsWith('getLineProgramJointPage_')).length
  const saveAt = performance.now()
  await modal.getByLabel(`F${count} · УЗК`, { exact: true }).selectOption('да')
  await modal.getByRole('button', { name: 'Проверить изменения', exact: true }).click()
  await expect(modal.getByRole('button', { name: 'Сохранить назначения', exact: true })).toBeVisible()
  const ack = modal.getByRole('checkbox', { name: /Подтверждаю назначение/ }); if (await ack.count()) await ack.check()
  await modal.getByRole('button', { name: 'Сохранить назначения', exact: true }).click()
  await expect(modal.getByText('Назначения сохранены · стыков: 1', { exact: true })).toBeVisible()
  const saveMs = Math.round(performance.now() - saveAt)
  await expect.poll(() => calls.filter(name => name.startsWith('getLineProgramJointPage_')).length).toBe(reads + 1)
  await page.evaluate(() => { window.dispatchEvent(new Event('focus')); window.dispatchEvent(new Event('online')) })
  await expect(modal.getByLabel(`F${count} · УЗК`, { exact: true })).toHaveValue('да')
  expect(calls.filter(name => name.startsWith('getLineProgramSection_'))).toHaveLength(1)
  expect(calls.filter(name => name.startsWith('getLineProgramJointPage_'))).toHaveLength(2)
  expect(calls.filter(name => name.startsWith('previewLineProgramControl_'))).toHaveLength(1)
  expect(calls.filter(name => name.startsWith('applyLineProgramControl_'))).toHaveLength(1)
  expect(errors).toEqual([])
  const responseBytes = await Promise.all(bytes)
  expect(responseBytes.every(size => size < count * 3000)).toBe(true)
  console.log(JSON.stringify({ lineSize: count, openedMs, searchMs, saveMs, detailResponseBytes: responseBytes, detailsRequests: 2 }))
})
