CREATE TABLE "dispatcher_accepted_warnings" (
	"key" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"title" text,
	"accepted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "duplicate_controls" (
	"id" serial PRIMARY KEY NOT NULL,
	"weld_joint_id" integer NOT NULL,
	"method" text NOT NULL,
	"result" text NOT NULL,
	"control_date" date,
	"conclusion" text,
	"conclusion_date" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "weld_joints" (
	"id" serial PRIMARY KEY NOT NULL,
	"weld_date" date,
	"project_title" text,
	"subtitle_code" text,
	"line" text,
	"group_name" text,
	"category" text,
	"psto_required" text,
	"weld_control_percent" numeric(12, 3),
	"isometry" text,
	"sheet" numeric(12, 3),
	"revision_number" numeric(12, 3),
	"joint" text,
	"spool" text,
	"spool_id" text,
	"status" text,
	"revision_actuality" text,
	"order_code_1" text,
	"order_code_2" text,
	"material_unique_number_1" text,
	"material_unique_number_2" text,
	"element_1" text,
	"element_2" text,
	"material_id_1" text,
	"material_id_2" text,
	"material_1" text,
	"material_2" text,
	"material_full_name_1" text,
	"material_full_name_2" text,
	"material_normative_document_1" text,
	"material_normative_document_2" text,
	"material_certificate_number_1" text,
	"material_certificate_number_2" text,
	"welding_method" text,
	"connection_type" text,
	"d1" numeric(12, 3),
	"d2" numeric(12, 3),
	"t1" numeric(12, 3),
	"t2" numeric(12, 3),
	"wdi" numeric(12, 3),
	"responsible" text,
	"stamp_1_k" text,
	"stamp_1_z" text,
	"stamp_1_o" text,
	"stamp_2_k" text,
	"stamp_2_z" text,
	"stamp_2_o" text,
	"stamp_1_k_fact" text,
	"stamp_1_z_fact" text,
	"stamp_1_o_fact" text,
	"stamp_2_k_fact" text,
	"stamp_2_z_fact" text,
	"stamp_2_o_fact" text,
	"has_vik" text,
	"has_rk" text,
	"has_pvk" text,
	"has_uzk" text,
	"has_tvmt" text,
	"has_rfa" text,
	"has_stls" text,
	"has_mkk" text,
	"vik_request" text,
	"rk_request" text,
	"pvk_request" text,
	"uzk_request" text,
	"psto_request" text,
	"tvmt_request" text,
	"rfa_request" text,
	"stls_request" text,
	"mkk_request" text,
	"psto_date" date,
	"heat_treatment_diagram" text,
	"psto_result" text,
	"psto_note" text,
	"vik_result" text,
	"rk_result" text,
	"pvk_result" text,
	"uzk_result" text,
	"tvmt_result" text,
	"rfa_result" text,
	"stls_result" text,
	"mkk_result" text,
	"vik_conclusion_date" date,
	"vik_conclusion" text,
	"rk_conclusion_date" date,
	"rk_conclusion" text,
	"pvk_conclusion_date" date,
	"pvk_conclusion" text,
	"uzk_conclusion_date" date,
	"uzk_conclusion" text,
	"tvmt_conclusion_date" date,
	"tvmt_conclusion" text,
	"rfa_conclusion_date" date,
	"rfa_conclusion" text,
	"stls_conclusion_date" date,
	"stls_conclusion" text,
	"mkk_conclusion_date" date,
	"mkk_conclusion" text,
	"lnk_defect_description" text,
	"lnk_note" text,
	"final_status" text,
	"boq" text,
	"ks3" text,
	"psto_boq" text,
	"psto_ks3" text,
	"psto_created_at" timestamp with time zone,
	"lnk_created_at" timestamp with time zone,
	"vik_boq" text,
	"vik_ks3" text,
	"rk_boq" text,
	"rk_ks3" text,
	"pvk_boq" text,
	"pvk_ks3" text,
	"uzk_boq" text,
	"uzk_ks3" text,
	"tvmt_boq" text,
	"tvmt_ks3" text,
	"rfa_boq" text,
	"rfa_ks3" text,
	"stls_boq" text,
	"stls_ks3" text,
	"mkk_boq" text,
	"mkk_ks3" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "welder_stamp_suspensions" (
	"id" serial PRIMARY KEY NOT NULL,
	"naks_stamp" text NOT NULL,
	"suspended_from" date NOT NULL,
	"suspended_to" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "welder_stamps" (
	"id" serial PRIMARY KEY NOT NULL,
	"naks_stamp" text,
	"welder_name" text,
	"internal_stamp" text,
	"weld_type" text,
	"diameter_from" text,
	"diameter_to" text,
	"valid_from" date,
	"valid_to" date,
	"archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "duplicate_controls" ADD CONSTRAINT "duplicate_controls_weld_joint_id_weld_joints_id_fk" FOREIGN KEY ("weld_joint_id") REFERENCES "public"."weld_joints"("id") ON DELETE cascade ON UPDATE no action;