CREATE TABLE "weld_joints" (
	"id" serial PRIMARY KEY NOT NULL,
	"weld_date" date,
	"project_title" text,
	"subtitle_code" text,
	"line" text,
	"group_name" text,
	"category" text,
	"psto_required" text,
	"weld_control_percent" numeric(12, 3),
	"isometry" text,
	"sheet" numeric(12, 3),
	"revision_number" numeric(12, 3),
	"joint_zone" text,
	"joint_nominal" numeric(12, 3),
	"index_code" text,
	"rw_joint" text,
	"joint" text,
	"spool_number" numeric(12, 3),
	"spool" text,
	"spool_id" text,
	"status" text,
	"revision_actuality" text,
	"order_code_1" text,
	"order_code_2" text,
	"element_1" text,
	"element_2" text,
	"material_id_1" text,
	"material_id_2" text,
	"material_1" text,
	"material_2" text,
	"welding_method" text,
	"connection_type" text,
	"d1" numeric(12, 3),
	"d2" numeric(12, 3),
	"t1" numeric(12, 3),
	"t2" numeric(12, 3),
	"wdi" numeric(12, 3),
	"responsible" text,
	"stamp_1_k" text,
	"stamp_1_zo" text,
	"stamp_2_k" text,
	"stamp_2_zo" text,
	"stamp_1_k_fact" text,
	"stamp_1_zo_fact" text,
	"stamp_2_k_fact" text,
	"stamp_2_zo_fact" text,
	"has_vik" boolean,
	"has_rk" boolean,
	"has_pvk" boolean,
	"has_uzk" boolean,
	"has_tvmt" boolean,
	"has_rfa" boolean,
	"has_stls" boolean,
	"psto_request" text,
	"lnk_request" text,
	"psto_result" text,
	"vik_result" text,
	"rk_result" text,
	"pvk_result" text,
	"uzk_result" text,
	"tvmt_result" text,
	"stls_result" text,
	"mkk_result" text,
	"final_status" text,
	"boq" text,
	"ks3" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
