ALTER TABLE "weld_joints"
  ALTER COLUMN "has_vik" TYPE text USING CASE WHEN "has_vik" IS TRUE THEN 'да' ELSE NULL END,
  ALTER COLUMN "has_rk" TYPE text USING CASE WHEN "has_rk" IS TRUE THEN 'да' ELSE NULL END,
  ALTER COLUMN "has_pvk" TYPE text USING CASE WHEN "has_pvk" IS TRUE THEN 'да' ELSE NULL END,
  ALTER COLUMN "has_uzk" TYPE text USING CASE WHEN "has_uzk" IS TRUE THEN 'да' ELSE NULL END,
  ALTER COLUMN "has_tvmt" TYPE text USING CASE WHEN "has_tvmt" IS TRUE THEN 'да' ELSE NULL END,
  ALTER COLUMN "has_rfa" TYPE text USING CASE WHEN "has_rfa" IS TRUE THEN 'да' ELSE NULL END,
  ALTER COLUMN "has_stls" TYPE text USING CASE WHEN "has_stls" IS TRUE THEN 'да' ELSE NULL END,
  ALTER COLUMN "has_mkk" TYPE text USING CASE WHEN "has_mkk" IS TRUE THEN 'да' ELSE NULL END;
