ALTER TABLE "weld_joints" ADD COLUMN "status" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "has_rfa" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "has_stls" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "has_mkk" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "rfa_control_basis" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "stls_control_basis" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "mkk_control_basis" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "rfa_request" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "rfa_request_date" date;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "stls_request" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "stls_request_date" date;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "mkk_request" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "mkk_request_date" date;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "rfa_result" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "stls_result" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "mkk_result" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "rfa_conclusion_date" date;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "rfa_conclusion" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "stls_conclusion_date" date;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "stls_conclusion" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "mkk_conclusion_date" date;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "mkk_conclusion" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "rfa_boq" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "rfa_ks3" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "stls_boq" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "stls_ks3" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "mkk_boq" text;--> statement-breakpoint
ALTER TABLE "weld_joints" ADD COLUMN "mkk_ks3" text;