import { boolean, date, integer, numeric, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

const numericNumber = (name: string) => numeric(name, { precision: 12, scale: 3, mode: 'number' })

export const weldJoints = pgTable('weld_joints', {
  id: serial('id').primaryKey(),
  weldDate: date('weld_date'),
  projectTitle: text('project_title'),
  subtitleCode: text('subtitle_code'),
  line: text('line'),
  groupName: text('group_name'),
  category: text('category'),
  pstoRequired: text('psto_required'),
  weldControlPercent: numericNumber('weld_control_percent'),
  isometry: text('isometry'),
  sheet: numericNumber('sheet'),
  revisionNumber: numericNumber('revision_number'),
  joint: text('joint'),
  spool: text('spool'),
  spoolId: text('spool_id'),
  status: text('status'),
  revisionActuality: text('revision_actuality'),
  orderCode1: text('order_code_1'),
  orderCode2: text('order_code_2'),
  materialUniqueNumber1: text('material_unique_number_1'),
  materialUniqueNumber2: text('material_unique_number_2'),
  element1: text('element_1'),
  element2: text('element_2'),
  materialId1: text('material_id_1'),
  materialId2: text('material_id_2'),
  material1: text('material_1'),
  material2: text('material_2'),
  materialFullName1: text('material_full_name_1'),
  materialFullName2: text('material_full_name_2'),
  materialNormativeDocument1: text('material_normative_document_1'),
  materialNormativeDocument2: text('material_normative_document_2'),
  materialCertificateNumber1: text('material_certificate_number_1'),
  materialCertificateNumber2: text('material_certificate_number_2'),
  weldingMethod: text('welding_method'),
  connectionType: text('connection_type'),
  materialGroup: text('material_group'),
  d1: numericNumber('d1'),
  d2: numericNumber('d2'),
  t1: numericNumber('t1'),
  t2: numericNumber('t2'),
  wdi: numericNumber('wdi'),
  responsible: text('responsible'),
  stamp1K: text('stamp_1_k'),
  stamp1Z: text('stamp_1_z'),
  stamp1O: text('stamp_1_o'),
  stamp2K: text('stamp_2_k'),
  stamp2Z: text('stamp_2_z'),
  stamp2O: text('stamp_2_o'),
  stamp1KFact: text('stamp_1_k_fact'),
  stamp1ZFact: text('stamp_1_z_fact'),
  stamp1OFact: text('stamp_1_o_fact'),
  stamp2KFact: text('stamp_2_k_fact'),
  stamp2ZFact: text('stamp_2_z_fact'),
  stamp2OFact: text('stamp_2_o_fact'),
  hasVik: text('has_vik'),
  hasRk: text('has_rk'),
  hasPvk: text('has_pvk'),
  hasUzk: text('has_uzk'),
  hasTvmt: text('has_tvmt'),
  hasRfa: text('has_rfa'),
  hasStls: text('has_stls'),
  hasMkk: text('has_mkk'),
  vikRequest: text('vik_request'),
  vikRequestDate: date('vik_request_date'),
  rkRequest: text('rk_request'),
  rkRequestDate: date('rk_request_date'),
  pvkRequest: text('pvk_request'),
  pvkRequestDate: date('pvk_request_date'),
  uzkRequest: text('uzk_request'),
  uzkRequestDate: date('uzk_request_date'),
  pstoRequest: text('psto_request'),
  pstoRequestDate: date('psto_request_date'),
  tvmtRequest: text('tvmt_request'),
  tvmtRequestDate: date('tvmt_request_date'),
  rfaRequest: text('rfa_request'),
  rfaRequestDate: date('rfa_request_date'),
  stlsRequest: text('stls_request'),
  stlsRequestDate: date('stls_request_date'),
  mkkRequest: text('mkk_request'),
  mkkRequestDate: date('mkk_request_date'),
  pstoDate: date('psto_date'),
  heatTreatmentDiagram: text('heat_treatment_diagram'),
  pstoResult: text('psto_result'),
  pstoNote: text('psto_note'),
  vikResult: text('vik_result'),
  rkResult: text('rk_result'),
  pvkResult: text('pvk_result'),
  uzkResult: text('uzk_result'),
  tvmtResult: text('tvmt_result'),
  rfaResult: text('rfa_result'),
  stlsResult: text('stls_result'),
  mkkResult: text('mkk_result'),
  vikConclusionDate: date('vik_conclusion_date'),
  vikConclusion: text('vik_conclusion'),
  rkConclusionDate: date('rk_conclusion_date'),
  rkConclusion: text('rk_conclusion'),
  pvkConclusionDate: date('pvk_conclusion_date'),
  pvkConclusion: text('pvk_conclusion'),
  uzkConclusionDate: date('uzk_conclusion_date'),
  uzkConclusion: text('uzk_conclusion'),
  tvmtConclusionDate: date('tvmt_conclusion_date'),
  tvmtConclusion: text('tvmt_conclusion'),
  rfaConclusionDate: date('rfa_conclusion_date'),
  rfaConclusion: text('rfa_conclusion'),
  stlsConclusionDate: date('stls_conclusion_date'),
  stlsConclusion: text('stls_conclusion'),
  mkkConclusionDate: date('mkk_conclusion_date'),
  mkkConclusion: text('mkk_conclusion'),
  lnkDefectDescription: text('lnk_defect_description'),
  lnkNote: text('lnk_note'),
  finalStatus: text('final_status'),
  testContour: text('test_contour'),
  testDate: date('test_date'),
  boq: text('boq'),
  testBoq: text('test_boq'),
  ks3: text('ks3'),
  testKs3: text('test_ks3'),
  pstoBoq: text('psto_boq'),
  pstoKs3: text('psto_ks3'),
  pstoCreatedAt: timestamp('psto_created_at', { withTimezone: true }),
  lnkCreatedAt: timestamp('lnk_created_at', { withTimezone: true }),
  vikBoq: text('vik_boq'),
  vikKs3: text('vik_ks3'),
  rkBoq: text('rk_boq'),
  rkKs3: text('rk_ks3'),
  pvkBoq: text('pvk_boq'),
  pvkKs3: text('pvk_ks3'),
  uzkBoq: text('uzk_boq'),
  uzkKs3: text('uzk_ks3'),
  tvmtBoq: text('tvmt_boq'),
  tvmtKs3: text('tvmt_ks3'),
  rfaBoq: text('rfa_boq'),
  rfaKs3: text('rfa_ks3'),
  stlsBoq: text('stls_boq'),
  stlsKs3: text('stls_ks3'),
  mkkBoq: text('mkk_boq'),
  mkkKs3: text('mkk_ks3'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export type WeldJoint = typeof weldJoints.$inferSelect
export type NewWeldJoint = typeof weldJoints.$inferInsert

export const welderStamps = pgTable('welder_stamps', {
  id: serial('id').primaryKey(),
  naksStamp: text('naks_stamp'),
  welderName: text('welder_name'),
  internalStamp: text('internal_stamp'),
  weldType: text('weld_type'),
  materialGroups: text('material_groups'),
  diameterFrom: text('diameter_from'),
  diameterTo: text('diameter_to'),
  thicknessFrom: text('thickness_from'),
  thicknessTo: text('thickness_to'),
  validFrom: date('valid_from'),
  validTo: date('valid_to'),
  naksPermits: text('naks_permits'),
  dlsPermits: text('dls_permits'),
  archived: boolean('archived').default(false).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export type WelderStamp = typeof welderStamps.$inferSelect
export type NewWelderStamp = typeof welderStamps.$inferInsert

export const welderStampSuspensions = pgTable('welder_stamp_suspensions', {
  id: serial('id').primaryKey(),
  naksStamp: text('naks_stamp').notNull(),
  suspendedFrom: date('suspended_from').notNull(),
  suspendedTo: date('suspended_to'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export type WelderStampSuspension = typeof welderStampSuspensions.$inferSelect
export type NewWelderStampSuspension = typeof welderStampSuspensions.$inferInsert

export const duplicateControls = pgTable('duplicate_controls', {
  id: serial('id').primaryKey(),
  weldJointId: integer('weld_joint_id')
    .notNull()
    .references(() => weldJoints.id, { onDelete: 'cascade' }),
  method: text('method').notNull(),
  result: text('result').notNull(),
  controlDate: date('control_date'),
  conclusion: text('conclusion'),
  conclusionDate: date('conclusion_date'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export type DuplicateControl = typeof duplicateControls.$inferSelect
export type NewDuplicateControl = typeof duplicateControls.$inferInsert

export const dispatcherAcceptedWarnings = pgTable('dispatcher_accepted_warnings', {
  key: text('key').primaryKey(),
  kind: text('kind').notNull(),
  title: text('title'),
  acceptedAt: timestamp('accepted_at', { withTimezone: true }).defaultNow().notNull(),
})

export type DispatcherAcceptedWarning = typeof dispatcherAcceptedWarnings.$inferSelect
export type NewDispatcherAcceptedWarning = typeof dispatcherAcceptedWarnings.$inferInsert
