import { boolean, date, numeric, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

const numericNumber = (name: string) => numeric(name, { precision: 12, scale: 3, mode: 'number' })

export const weldJoints = pgTable('weld_joints', {
  id: serial('id').primaryKey(),
  weldDate: date('weld_date'),
  projectTitle: text('project_title'),
  subtitleCode: text('subtitle_code'),
  line: text('line'),
  groupName: text('group_name'),
  category: text('category'),
  pstoRequired: text('psto_required'),
  weldControlPercent: numericNumber('weld_control_percent'),
  isometry: text('isometry'),
  sheet: numericNumber('sheet'),
  revisionNumber: numericNumber('revision_number'),
  jointZone: text('joint_zone'),
  jointNominal: numericNumber('joint_nominal'),
  indexCode: text('index_code'),
  rwJoint: text('rw_joint'),
  joint: text('joint'),
  spoolNumber: numericNumber('spool_number'),
  spool: text('spool'),
  spoolId: text('spool_id'),
  status: text('status'),
  revisionActuality: text('revision_actuality'),
  orderCode1: text('order_code_1'),
  orderCode2: text('order_code_2'),
  element1: text('element_1'),
  element2: text('element_2'),
  materialId1: text('material_id_1'),
  materialId2: text('material_id_2'),
  material1: text('material_1'),
  material2: text('material_2'),
  weldingMethod: text('welding_method'),
  connectionType: text('connection_type'),
  d1: numericNumber('d1'),
  d2: numericNumber('d2'),
  t1: numericNumber('t1'),
  t2: numericNumber('t2'),
  wdi: numericNumber('wdi'),
  responsible: text('responsible'),
  stamp1K: text('stamp_1_k'),
  stamp1Z: text('stamp_1_z'),
  stamp1O: text('stamp_1_o'),
  stamp2K: text('stamp_2_k'),
  stamp2Z: text('stamp_2_z'),
  stamp2O: text('stamp_2_o'),
  stamp1KFact: text('stamp_1_k_fact'),
  stamp1ZFact: text('stamp_1_z_fact'),
  stamp1OFact: text('stamp_1_o_fact'),
  stamp2KFact: text('stamp_2_k_fact'),
  stamp2ZFact: text('stamp_2_z_fact'),
  stamp2OFact: text('stamp_2_o_fact'),
  hasVik: boolean('has_vik'),
  hasRk: boolean('has_rk'),
  hasPvk: boolean('has_pvk'),
  hasUzk: boolean('has_uzk'),
  hasTvmt: boolean('has_tvmt'),
  hasRfa: boolean('has_rfa'),
  hasStls: boolean('has_stls'),
  hasMkk: boolean('has_mkk'),
  vikRequest: text('vik_request'),
  rkRequest: text('rk_request'),
  pvkRequest: text('pvk_request'),
  uzkRequest: text('uzk_request'),
  pstoRequest: text('psto_request'),
  tvmtRequest: text('tvmt_request'),
  rfaRequest: text('rfa_request'),
  stlsRequest: text('stls_request'),
  mkkRequest: text('mkk_request'),
  pstoDate: date('psto_date'),
  heatTreatmentDiagram: text('heat_treatment_diagram'),
  pstoResult: text('psto_result'),
  pstoNote: text('psto_note'),
  vikResult: text('vik_result'),
  rkResult: text('rk_result'),
  pvkResult: text('pvk_result'),
  uzkResult: text('uzk_result'),
  tvmtResult: text('tvmt_result'),
  rfaResult: text('rfa_result'),
  stlsResult: text('stls_result'),
  mkkResult: text('mkk_result'),
  vikConclusionDate: date('vik_conclusion_date'),
  vikConclusion: text('vik_conclusion'),
  rkConclusionDate: date('rk_conclusion_date'),
  rkConclusion: text('rk_conclusion'),
  pvkConclusionDate: date('pvk_conclusion_date'),
  pvkConclusion: text('pvk_conclusion'),
  uzkConclusionDate: date('uzk_conclusion_date'),
  uzkConclusion: text('uzk_conclusion'),
  tvmtConclusionDate: date('tvmt_conclusion_date'),
  tvmtConclusion: text('tvmt_conclusion'),
  rfaConclusionDate: date('rfa_conclusion_date'),
  rfaConclusion: text('rfa_conclusion'),
  stlsConclusionDate: date('stls_conclusion_date'),
  stlsConclusion: text('stls_conclusion'),
  mkkConclusionDate: date('mkk_conclusion_date'),
  mkkConclusion: text('mkk_conclusion'),
  lnkDefectDescription: text('lnk_defect_description'),
  lnkNote: text('lnk_note'),
  finalStatus: text('final_status'),
  boq: text('boq'),
  ks3: text('ks3'),
  pstoBoq: text('psto_boq'),
  pstoKs3: text('psto_ks3'),
  pstoCreatedAt: timestamp('psto_created_at', { withTimezone: true }),
  lnkCreatedAt: timestamp('lnk_created_at', { withTimezone: true }),
  vikBoq: text('vik_boq'),
  vikKs3: text('vik_ks3'),
  rkBoq: text('rk_boq'),
  rkKs3: text('rk_ks3'),
  pvkBoq: text('pvk_boq'),
  pvkKs3: text('pvk_ks3'),
  uzkBoq: text('uzk_boq'),
  uzkKs3: text('uzk_ks3'),
  tvmtBoq: text('tvmt_boq'),
  tvmtKs3: text('tvmt_ks3'),
  rfaBoq: text('rfa_boq'),
  rfaKs3: text('rfa_ks3'),
  stlsBoq: text('stls_boq'),
  stlsKs3: text('stls_ks3'),
  mkkBoq: text('mkk_boq'),
  mkkKs3: text('mkk_ks3'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export type WeldJoint = typeof weldJoints.$inferSelect
export type NewWeldJoint = typeof weldJoints.$inferInsert
