import { boolean, date, numeric, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

const numericNumber = (name: string) => numeric(name, { precision: 12, scale: 3, mode: 'number' })

export const weldJoints = pgTable('weld_joints', {
  id: serial('id').primaryKey(),
  weldDate: date('weld_date'),
  projectTitle: text('project_title'),
  subtitleCode: text('subtitle_code'),
  line: text('line'),
  groupName: text('group_name'),
  category: text('category'),
  pstoRequired: text('psto_required'),
  weldControlPercent: numericNumber('weld_control_percent'),
  isometry: text('isometry'),
  sheet: numericNumber('sheet'),
  revisionNumber: numericNumber('revision_number'),
  jointZone: text('joint_zone'),
  jointNominal: numericNumber('joint_nominal'),
  indexCode: text('index_code'),
  rwJoint: text('rw_joint'),
  joint: text('joint'),
  spoolNumber: numericNumber('spool_number'),
  spool: text('spool'),
  spoolId: text('spool_id'),
  status: text('status'),
  revisionActuality: text('revision_actuality'),
  orderCode1: text('order_code_1'),
  orderCode2: text('order_code_2'),
  element1: text('element_1'),
  element2: text('element_2'),
  materialId1: text('material_id_1'),
  materialId2: text('material_id_2'),
  material1: text('material_1'),
  material2: text('material_2'),
  weldingMethod: text('welding_method'),
  connectionType: text('connection_type'),
  d1: numericNumber('d1'),
  d2: numericNumber('d2'),
  t1: numericNumber('t1'),
  t2: numericNumber('t2'),
  wdi: numericNumber('wdi'),
  responsible: text('responsible'),
  stamp1K: text('stamp_1_k'),
  stamp1Zo: text('stamp_1_zo'),
  stamp2K: text('stamp_2_k'),
  stamp2Zo: text('stamp_2_zo'),
  stamp1KFact: text('stamp_1_k_fact'),
  stamp1ZoFact: text('stamp_1_zo_fact'),
  stamp2KFact: text('stamp_2_k_fact'),
  stamp2ZoFact: text('stamp_2_zo_fact'),
  hasVik: boolean('has_vik'),
  hasRk: boolean('has_rk'),
  hasPvk: boolean('has_pvk'),
  hasUzk: boolean('has_uzk'),
  hasTvmt: boolean('has_tvmt'),
  hasRfa: boolean('has_rfa'),
  hasStls: boolean('has_stls'),
  hasMkk: boolean('has_mkk'),
  vikRequest: text('vik_request'),
  rkRequest: text('rk_request'),
  pvkRequest: text('pvk_request'),
  uzkRequest: text('uzk_request'),
  pstoRequest: text('psto_request'),
  tvmtRequest: text('tvmt_request'),
  rfaRequest: text('rfa_request'),
  stlsRequest: text('stls_request'),
  mkkRequest: text('mkk_request'),
  pstoDate: date('psto_date'),
  heatTreatmentDiagram: text('heat_treatment_diagram'),
  pstoResult: text('psto_result'),
  pstoNote: text('psto_note'),
  vikResult: text('vik_result'),
  rkResult: text('rk_result'),
  pvkResult: text('pvk_result'),
  uzkResult: text('uzk_result'),
  tvmtResult: text('tvmt_result'),
  rfaResult: text('rfa_result'),
  stlsResult: text('stls_result'),
  mkkResult: text('mkk_result'),
  finalStatus: text('final_status'),
  boq: text('boq'),
  ks3: text('ks3'),
  pstoBoq: text('psto_boq'),
  pstoKs3: text('psto_ks3'),
  pstoCreatedAt: timestamp('psto_created_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export type WeldJoint = typeof weldJoints.$inferSelect
export type NewWeldJoint = typeof weldJoints.$inferInsert
