export {
  WORKFLOW_DIALOG_HEIGHT_CLASS as LNK_WORKFLOW_DIALOG_HEIGHT_CLASS,
  WORKFLOW_DIALOG_WIDTH_CLASS as LNK_WORKFLOW_DIALOG_WIDTH_CLASS,
  WORKFLOW_MANAGER_DIALOG_HEIGHT_CLASS as LNK_MANAGER_DIALOG_HEIGHT_CLASS,
  WORKFLOW_MANAGER_DIALOG_WIDTH_CLASS as LNK_MANAGER_DIALOG_WIDTH_CLASS,
} from '@/components/workflow-dialog-layout'

export const LNK_RESULT_ROW_GRID_CLASS =
  'grid-cols-[28px_minmax(360px,1.05fr)_minmax(320px,0.95fr)_220px_32px]'
